#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# NOTE: take care to keep the syntax bash compatible
#

# webserver port
port=1976

# log files
web_logfile="var/access.log"
app_logfile="var/application.log"
sql_logfile="var/sql.log"

# session defaults
session_salt="87525f4c-af0e-47ee-81c2-144dfsgfca0b"
session_timeout=86400 #24 * 60 * 60, # 24 hours   in seconds
session_dir='var'
# session_name="framework" # autogenerated from meta["name"]
session_cookie_domain=None
session_ignore_expiry=True
session_ignore_change_ip=False
session_expired_message='Session expired'

baseurl='' # set this if you use a reverse proxy

smtp="mail.usb.ch"

#tns_str="(DESCRIPTION = (FAILOVER = ON)(LOAD_BALANCE = OFF)(ENABLE=BROKEN)(ADDRESS_LIST = (ADDRESS = (PROTOCOL = TCP)(HOST = oraisop.uhbs.ch)(PORT = 1545))(ADDRESS = (PROTOCOL = TCP)(HOST = oraisop2.uhbs.ch)(PORT = 1545)))(CONNECT_DATA =(SERVICE_NAME = ISOP_PRI.WORLD)(failover_mode=(type=select) (method=basic))))"

